### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by zaie** [suyogduttjain/fusionseg#5]
I've emailed you but I didn't receive any reply. So I have to raise an issue here. Hope it won't bother you too much. 
I want to use your YOUTUBE OBJECTS DATASET (PIXEL LEVEL OBJECT MASKS). But I cannot match it with the original youtube objects dataset.
For example, how can I find the image "ROOT OF masks\youtube_masks\aeroplane\data\0012\shots\001\images\00001.jpg" in the original youtube objects dataset? I tried to match this image with the first image in video "0012" ,shot "001", using the range files from the original dataset. But it's wrong.
I know it's a stupid question but I really cannot start my experiment without the matching. 
Thank you!

**Comment by suyogduttjain** [comment]
Using Youtube-Objects - v1 solves the problem.
